###
# Defaults


###
# Templating

featureTeamName: apollon

image_template: &common_image
  pullPolicy: IfNotPresent

common_template: &common
  aadPodIdBinding: aks-dmp-infogreffe-frc-dev-agentpool
  featureTeamName: apollon
  autoscaling:
    enabled: false #TODO rework it when in DEV


keycloak:
  <<: *common
  nameOverride: keycloak
  image:
    <<: *common_image
    repository: nginx
    tag: latest
  replicaCount: 3
  is_keycloak: true

  resources:
    limits:
      cpu: 3500m
      memory: 2048Mi
    requests:
      cpu: 800m
      memory: 512Mi  

  ## Deploy Keycloak Deployment Vs StatefulSet
  deploy_statefulset:
    enabled: true

  env:
    # KC_hostname-admin => The hostname for accessing the administration console.
    # KC_hostname-admin-url => Set the base URL for accessing the administration console, including scheme, host, port and path
    #KC_HOSTNAME: https://www.api.infogreffe.fr/
    #KC_HOSTNAME_PATH: apollon/keycloak
    KC_HOSTNAME_ADMIN_URL: https://www.preprod-api.infogreffe.fr/apollon/keycloak
    KC_HOSTNAME_URL: https://www.preprod-api.infogreffe.fr/apollon/keycloak
    #KC_HOSTNAME_PORT: 8080
    KC_DB: postgres
    KC_CACHE: local
    KC_PROXY: edge
    KC_HOSTNAME_STRICT: false
    KC_SPI_EMAIL_TEMPLATE_APOLLON_MAIL_SENDER_BLACKLIST_EMAIL_PATTERNS: ".*(@mjl.gouv.fr)$"
    KC_SPI_EVENTS_LISTENER_USER_PROFILE_UPDATE_EVENT_LISTENER_MS_COMPTE_CLIENT_BASE_URL: "http://apollon-compte-client.apollon.svc.cluster.local:8080/v1/comptes_clients"
    KC_SPI_AUTHENTICATOR_AUTH_APOLLON_USERNAME_PASSWORD_FORM_BLACKLIST_EMAIL_PATTERNS: ".*(@mjl.gouv.fr)$"
    KC_SPI_AUTHENTICATOR_AUTH_APOLLON_USERNAME_PASSWORD_FORM_POSEIDON_URL: "https://www3.preprod.infogreffe.fr/services/user-service/api/users"
    KC_SPI_AUTHENTICATOR_AUTH_APOLLON_USERNAME_PASSWORD_FORM_POSEIDON_USERNAME: "not_used"  # inutile en prod
    KC_SPI_AUTHENTICATOR_AUTH_APOLLON_USERNAME_PASSWORD_FORM_POSEIDON_PASSWORD: "not_used"  # inutile en prod
    KC_SPI_AUTHENTICATOR_AUTH_APOLLON_USERNAME_PASSWORD_FORM_CODE_TVA_URL: "https://www.preprod-api.infogreffe.fr/hermes/paniers/api/v1/tva/code"
    KC_SPI_AUTHENTICATOR_AUTH_APOLLON_USERNAME_PASSWORD_FORM_MS_COMPTE_CLIENT_BASE_URL: "http://apollon-compte-client.apollon.svc.cluster.local:8080/v1/comptes_clients"
    ## new keycloak version
    KC_DB_URL: "jdbc:postgresql://psqlf-dmp-infogreffe-frc-preprod-apollon.postgres.database.azure.com:5432/keycloak?sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory"
    KC_DB_USERNAME: claranet
    KC_DB_URL_DATABASE: keycloak
    KEYCLOAK_ADMIN: admin
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=6c8ee613-097c-409a-96db-8ef6e2d5a3b3;IngestionEndpoint=https://francecentral-0.in.applicationinsights.azure.com/;LiveEndpoint=https://francecentral.livediagnostics.monitor.azure.com/"

    APPLICATIONINSIGHTS_ROLE_NAME: "apollon-keycloak-pprd"
    AZDEV: claranet
    DEBUG: true
    DEBUG_PORT: "*:8100"

  probe:
    liveness:
      httpPath: /admin
    startup:
      httpPath: /admin
