{{ if eq .Values.nameOverride  "integ-output-router"}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: infogreffe-managed-csi-premium
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS
  tags: app="dmp", applicationname="claranet - dmp", approver="infogreff@gmail.com", businessunit="impact", client="infogreffe", cost_center="claranet", costcenter="01212312", dr="essential", env="prod", git_repo="https://git.fr.clara.net/cmp-x19txb/internals/prj-klwdsk/terraform/dmp/fr-central/prod", maintainer="claranet", owner="claranet", provider="helm", serviceclass="gold", sfx_monitored="true", stack="app", team="isf-web"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: {{ include "api.fullname" . }}
#  namespace: apollon
#  labels:
#    app.kubernetes.io/name: {{ include "api.fullname" . }}
#    helm.sh/chart: {{ include "api.fullname" . }}
#    app.kubernetes.io/instance: {{ include "api.fullname" . }}
#spec:
#  storageClassName: infogreffe-managed-csi-premium
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#    storage: 5Gi
{{ end }}
